# Generated by Django 3.0.5 on 2020-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
