# Generated by Django 3.0.5 on 2020-04-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
