# Generated by Django 3.0.5 on 2020-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(verbose_name='Date played'),
        ),
        migrations.AlterField(
            model_name='session',
            name='enjoyment',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], default='Low', max_length=1, verbose_name='Enjoyment level'),
        ),
    ]
