# Generated by Django 3.0.5 on 2020-04-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='enjoyment',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], default='m', max_length=1, verbose_name='Enjoyment level'),
        ),
    ]
