# Generated by Django 3.0.5 on 2020-04-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='label',
            field=models.CharField(default='quick', max_length=200),
            preserve_default=False,
        ),
    ]
