# Generated by Django 3.0.5 on 2020-04-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='label',
        ),
        migrations.AddField(
            model_name='game',
            name='label',
            field=models.ManyToManyField(to='main_app.Label'),
        ),
    ]
