# Generated by Django 3.0.5 on 2020-04-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200410_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='label',
            new_name='labels',
        ),
    ]
